### ISSUE TITLE
理论基础的md文件 图片打不开

### ISSUE THREAD

**Issue by daixd5520** [HarleysZhang/llm_profiler#2]

**Comment by harleyszhang** [comment]
看这个链接吧https://github.com/HarleysZhang/dl_note/blob/main/6-llm_note/transformer_basic/Transformer%E6%80%A7%E8%83%BD%E5%88%86%E6%9E%90%E7%90%86%E8%AE%BA%E5%9F%BA%E7%A1%80.md。
或者我上传的转换好的 pdf 文档。
[Transformer性能分析理论基础.pdf](https://github.com/user-attachments/files/16817391/Transformer.pdf)
